### PR TITLE
Comments and Edits from AJC

### PR DESCRIPTION
**Pull request by acaruana2009**
I have modified the TODO following the DE discussion, and added more points in after reading the rest of the paper. I have done some minor edits, and included the original DE reference for completeness.

### CODE REVIEW

**Review by arm61 — APPROVED** [review]

**Comment by arm61** [comment]
@acaruana2009 add yourself to the authors’ list!

**Comment by acaruana2009** [comment]
OK will do!

**Comment by andyfaff** [comment]
Commenting in a closed PR isn't the best way of communicating but:

> Should the appropriate handling of the roughness be expanded by giving some ideas of how to deal with large interfaces i.e. from interdiffusion, by slicing the interface? - [ ] It is good to make explicit that from too large roughness values not only the SLD you observe is unphysical, it also does not match the generated reflectivity simulation. This point is often missed. A few users I have spoken to think it is 'OK' to have a huge roughness because 'it gives the SLD profile they expect' missing the previous point.

I think widespread knowledge of good roughness treatments are still a wild west area for NR-XRR in terms of practice and tooling. When large roughnesses (compared to layer thicknesses) are used, such that the SLD of a layer in an SLD profile bears no resemblance to the modelled SLD value, *more often than not the micro-sliced reflectivity curve is almost indistinguishable from the Nevot-Croce calculated reflectivity curve from the model parameters*.

In those cases I don't think micro-slicing is not the panacea it's made out to be. What matters is:

- how the SLD profile is interpreted. For example, if you have a layer with SLD=3.47, roughness of 10, and a thickness of 20, and the SLDs on both sides are lower (0 and 2.07) then the SLD of that layer in an SLD profile will not be 3.47, it'll be much lower. The SLD profile is probably correct, in that the micro-sliced and Nevot-Croce reflectivities will both match data, but what is the true SLD value of the layer that should be reported?  Thus what's unphysical is not the SLD profile, it's probably a true reflection of the sample, what's unphysical is the interpretation of the model numbers used to generate the SLD profile. Micro-slicing doesn't prevent reporting of funny model numbers.

- good micro-slicing depends on generation of good SLD profiles. There is a surprising amount of variation in generation of sld profiles. For example https://arxiv.org/pdf/1801.04975.pdf would indicate that practice over time has changed. Has microslicing practice changed over time?

@acaruana2009 can you explain "it doesn't match the generated reflectivity simulation" a bit more?

I'd like to know the situations when people think microslicing needs to be resorted to. I think this is a view held in the reflectometry community for some situations, but as far as I know it's not written down anywhere.
I think the community could do with a good discussion of practices and thorough examination of situations where roughnesses are large compared to thickness.

**Comment by acaruana2009** [comment]
Thanks for the detailed response. I will write a more complete response in the issues page once I have gone through a load of simulations in Refl1d today. The short answer is, like you, I have found it mentioned very little, however it is mentioned here in the refl1d docs (https://refl1d.readthedocs.io/en/latest/api/experiment.html) under roughness_limit variable - albeit briefly. 

I work quite a bit with systems that are inter-diffuse, where in non-slicing models it wants to push the roughness values to truly non-physical values. When I then sliced these same models I found differences in the reflectivity curves - even for very fine slicing. Last night I ran a basic Air/Solid simulation of Si/Au - with d_Au = 50A and the roughness values of both the Si and Au = 50 A. When I take the difference over the sum for the 2 reflectivity curves I get a maximum difference of 5% for this model (the slices were 0.1A slices). 

In general, I agree with your points above and definitely this needs to be discussed more widely. There is a general assumption that although for the Nevot-Croce approximation the inputted SLD values (as you have described in 1.) may not mean what they once did, that the shape of the SLD is still valid - in my experience as I have explained above, at large roughness values, I have seen not insignificant differences between sliced and non-sliced profiles. 

I want to investigate this further today, and get less anecdotal and more solid examples of what I mean. Once I have the figures I will upload them.

**Pull request merged**
