### PR TITLE
Modified TODO.md to include comments about DE

### PR DESCRIPTION
**Pull request by acaruana2009**
I have included comments about how I will look into the DE section. I have also modified the title of the environment.yml file to match the readme instructions.

### CODE REVIEW

**Review by arm61 — COMMENTED** [review]
Just as a heads up, when I originally wrote the DE bit I (think I, it was a couple of years ago originally in my thesis and then modified for this) used the [Björck paper](https://journals.iucr.org/j/issues/2011/06/00/aj5178/aj5178.pdf) for the terminology.
Although this might not match with the Storn and Price terminology it is (probably) the most widely cited paper for the use in reflectometry so maybe it makes sense to keep it?

It can definitely do with a read over cause it is likely that is doesn't make a lot of sense...

**Comment by acaruana2009** [comment]
Totally understood. What I want to check is what GenX actually uses. I was under the impression it was a Genetic Algorithm not DE in which case it is mathematically different (to the best of my understanding) from DE as outlined by Storn and Price. Since RefNX, Refl1D and RasCal use DE (and I am sure many other fitting software) its good to make sure we have the distinction right - and if we feel it is useful, we may want to highlight both GA and DE anyway.

**Comment by arm61** [comment]
Interesting, and a very good point. I haven't used GenX so definitely worth checking out! I look forward to the contribution (and completely again that if we are mentioning either we should mention both!)

**Comment by aglavic** [comment]
GenX uses differential evolution (was actually the first as far as I know) and this IS a genetic algorithm (that's why it's called evolution). Most older programs user gradient decent (like Levenberg-Marquard) and as far as I understand RefNX can use anything provided by Scipy.

**Comment by acaruana2009** [comment]
Thank you for the clarification. I think where the confusion has been from my perspective, is that in several papers (including Storn and Price's 1997 paper DOI: 10.1023/A:1008202821328) they make a distinction between Genetic Algorithms and Evolution Strategies - they say that both belong to the broad class of evolutionary algorithms. Additionally, other papers (such as DOI: 10.1109/TAP.2014.2322880), have run comparisons of different GA's vs DE, and again made a distinction between the methods in the paper.

From a pragmatic perspective, now that you have clarified that GenX uses DE, the distinction doesn't matter for the purpose of this paper, but just to be aware that pure computational scientists working on optimization algorithms may also make the distinction in this way.

**Comment by arm61** [comment]
A very good point (and totally understandable confusion) @acaruana2009. I agree that the distinction is probably beyond the paper. 

[a computer scientist reacting to this paper](https://twitter.com/trivial__/status/1291119889969684480?s=21)

**Comment by andyfaff** [comment]
For the historical record:
Motofit was using differential evolution from around [~June 2007](https://github.com/IP-XOP/gencurvefit/commit/77f39573d43ab3ab533622a815d5a2dd13c269b5), before the GenX paper was published (I didn't write an article on that part). I'm not sure what GaRefl (NCNR) was doing at that point, but the GA stands for genetic algorithm I think, so there's a possibility another program might have been even earlier.

However, neither GenX or Motofit (or Garefl) were remotely the first software to use DE for reflectometry.
Way back in 1999 the [Wormington](Phil. Trans. R. Soc. Lond. A (1999) 357, 2827–2848) paper was the first article that explained differential evolution for reflectometry. So that article should be the grandparent use of DE for reflectometry.

**Comment by arm61** [comment]
Just for the (non-historical) record, in the text, the Wormington paper is cited alongside Björck’s paper specifically about differential evolution. I thought this was the best balance of history and information for the reader. Happy to include more if there is a desire for it.

**Pull request merged**
