### PR TITLE
MAINT: add sld.yml

### PR DESCRIPTION
**Pull request by andyfaff**
This is an example of what I'm thinking of. Early stages still. 

Would be nice to have a yaml validator in the CI, to make sure it has a proper format. In the meantime use https://codebeautify.org/yaml-validator.

### CODE REVIEW

**Comment by arm61** [comment]
Why not as json? More serializable, and based on what I am reading just now more suited to databases

**Comment by arm61** [comment]
But I 100 % prefer this sort of thing to excel workbooks 🤢

**Comment by andyfaff** [comment]
At this point it's important that it's easily editable in a text editor, json is less so, yaml more so.
It should be possible to convert between the two relatively easily.

**Comment by arm61** [comment]
Agh, humans ruining everything!...as usual. 

You are right though, we want something that people can update without being scared. 

Apparently this will convert **untested**.
```
stream = file('sld.yml', 'r')
yml_loaded = yaml.safe_load(stream)

with open('sld.json', 'wb') as f:
    json.dump(yml_loaded, f)
```

**Pull request merged**
