### PR TITLE
Fix up dynamical approach

### PR DESCRIPTION
**Pull request by andyfaff**
I'm not sure that the original equations that you had there were correct. I normally think about a characteristic matrix for each interface, which would result in the changes I just made.

- for 0 layers there is just one matrix
- for 1 layers there are two matrices
etc.

The normal wavevector was wrong, and `i` was missed out in the phase factor. (Or you can add it to the next equation).

### CODE REVIEW

**Comment by andyfaff** [comment]
It'd be good to get more eyes on this though.

**Comment by arm61** [comment]
Very good catches! (Don't tell my PhD assessors cause I think it was written the same way as I had it in my thesis...). 

As for additional eyes: @tomarnoldess, @bmaranville, @jfkcooper, @acaruana2009, @christykinane, @aglavic anyone got some free time?

I know that @wpotrzebowski is going to have a look this month

**Comment by andyfaff** [comment]
@arm61, auto committing changes to PDF and binary figures on every push is really going to bloat the repo if there are a lot of changes. Do you mind if we turn off the auto commit?

**Comment by arm61** [comment]
Doesn't bother me if it is turned off!

**Comment by arm61** [comment]
I am sorting it now!

**Comment by arm61** [comment]
That's it sorted now. I have decided to just have the source files in the repo and added instructions to build the paper.

**Comment by andyfaff** [comment]
It's probably fine to leave the build step in, just avoid committing the PDF/PNG/etc.

**Comment by acaruana2009** [comment]
Hi all, I have had a quick skim through the paper and there are a couple of minor things here and there I wouldn't mind commenting on but what would be the best way to do this?

More specifically, I wanted to check about defining differential evolution as a genetic algorithm. My understanding is that although DE and GA are both population based they work differently - it might be worth highlighting this point. I must admit i don't know if GA could be defined as a subset of DE though? 

I will try to pull together some literature to explain what I mean.

**Comment by arm61** [comment]
I am not sure about the precise definitions of genetic algorithms but differential *evolution* (being an evolutionary algorithm) was the reason for my wording. Though like I said definitely not an expert here. 

Best way to make contribution would be a pull request I reckon! Look forward to hearing your thoughts.

**Comment by andyfaff** [comment]
I would suggest a pull request in which you edit the document directly. Do you have experience with git?

**Comment by acaruana2009** [comment]
Not massively, but I do have GitHub Desktop installed. Should I fork the repo, make changes and then submit a pull request that way?

**Comment by andyfaff** [comment]
I would fork the repo, make a feature branch (git branch mybranch, git checkout mybranch), make the edits, git commit the edits, push the branch to your fork, make a pull request from your fork to the main repo.

**Comment by andyfaff** [comment]
https://scipy.github.io/devdocs/dev/contributor/development_workflow.html might give an idea.

**Comment by acaruana2009** [comment]
thanks for the info. I will have a go and let you know if I get stuck.

**Comment by bmaranville** [comment]
I recently set up a workflow in github actions where it builds and then updates the build artifact to an existing release.  Then the most recent PDF would be available for download from the releases page, and it won't clog the git history with big binary diffs.
(see https://github.com/reductus/reductus/blob/es6_modules/.github/workflows/client_build.yml)

**Comment by arm61** [comment]
This is a good idea @bmaranville, I have done a similar thing for another paper that I have worked on. Might give it a bash again

**Pull request merged**
